apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: sonar-deployment
   labels:
      app: test
      env: dev
   namespace: my-namespace
spec:
   replicas: 3
   selector:
      matchLabels:
        app: test
   template:
      metadata:
         labels:
            app: test
      spec:
        containers:
          - name: deployment-container
            image: dockerrock123/sonarqube:1.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
                protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: test
  namespace: my-namespace
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: test