apiVersion: apps/v1
kind: Deployment
metadata:
   name: sonar-deployment
   labels:
      app: test
      env: dev
   namespace: default
spec:
   replicas: 3
   selector:
      matchLabels:
        app: test
   template:
      metadata:
         labels:
            app: test
      spec:
        containers:
          - name: deployment-container
            image: dockerrock123/sonarqube:1.0
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
             - name: MESSAGE
               valueFrom:
                 configMapKeyRef:
                   name: k8s-configmap
                   key: message.test
            env:
              - name: MYSECRET_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysecret
                    key: test.password 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: test
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: test