apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar-config
  labels:
    app: sonar-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-config
  template:
    metadata:
      labels:
        app: sonar-config
    spec:
      containers:
      - name: sonar-config
        image: dockerrock123/sonarqube:1.0
        ports:
        - containerPort: 8080
        
---
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-config
  labels:
    app: sonar-config
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: sonar-config